language: node_js,
node_js:
  - "6"
before_script:
  - npm install
  - cd app
  - npm install
  - cd ..
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - node_modules/.bin/karma start karma.conf.js --single-run --browsers PhantomJS
